#!/usr/bin/env python3
"""
bundle.py — Kotlin competitive programming bundler.

Usage:
    python3 tools/bundle.py [Main.kt] [-o submit/Main.kt]

How it works:
1. Reads Main.kt (or the file specified).
2. Detects //%AUTO, //%include, //%exclude directives.
3. Loads tools/registry.json to map symbols → source files.
4. Scans Main.kt for references to registered symbols.
5. Resolves transitive dependencies.
6. Concatenates all snippet files above Main.kt body.
7. Writes submit/Main.kt (or the output path specified).
"""

import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
REGISTRY_PATH = REPO_ROOT / "tools" / "registry.json"
DEFAULT_MAIN = REPO_ROOT / "Main.kt"
DEFAULT_OUT = REPO_ROOT / "submit" / "Main.kt"


def load_registry(path: Path) -> dict[str, str]:
    """Returns {symbol: file_path} mapping."""
    with open(path) as f:
        reg = json.load(f)
    result: dict[str, str] = {}
    for file_path, symbols in reg.items():
        for sym in symbols:
            result[sym] = file_path
    return result


def read_file(path: Path) -> str:
    with open(path) as f:
        return f.read()


def parse_directives(main_src: str) -> tuple[list[str], list[str], bool]:
    """Parse //%include, //%exclude, //%AUTO from Main.kt.
    Returns (includes, excludes, has_auto).
    """
    includes: list[str] = []
    excludes: list[str] = []
    has_auto = False
    for line in main_src.splitlines():
        stripped = line.strip()
        if stripped == "//%AUTO":
            has_auto = True
        elif stripped.startswith("//%include "):
            includes.append(stripped[len("//%include "):].strip())
        elif stripped.startswith("//%exclude "):
            excludes.append(stripped[len("//%exclude "):].strip())
    return includes, excludes, has_auto


def find_referenced_symbols(main_src: str, registry: dict[str, str]) -> set[str]:
    """Find all registered symbols that appear in main_src."""
    # Strip directive comments to avoid false positives
    src = re.sub(r"//.*", "", main_src)
    found: set[str] = set()
    for sym in registry:
        # Match whole word
        if re.search(r"\b" + re.escape(sym) + r"\b", src):
            found.add(sym)
    return found


def resolve_deps(
    files_needed: set[str],
    registry: dict[str, str],
    sym_to_file: dict[str, str],
) -> list[str]:
    """Resolve files transitively by scanning each file for more symbols.
    Returns ordered list of files (dependencies first).
    """
    resolved: list[str] = []
    visited: set[str] = set()
    queue = list(files_needed)
    while queue:
        fpath = queue.pop(0)
        if fpath in visited:
            continue
        visited.add(fpath)
        full_path = REPO_ROOT / fpath
        if not full_path.exists():
            print(f"WARNING: {fpath} not found, skipping.", file=sys.stderr)
            continue
        src = read_file(full_path)
        # Find more symbols referenced in this file
        for sym, dep_file in sym_to_file.items():
            if dep_file != fpath and dep_file not in visited:
                if re.search(r"\b" + re.escape(sym) + r"\b", re.sub(r"//.*", "", src)):
                    queue.append(dep_file)
        resolved.append(fpath)
    return resolved


def strip_package(src: str) -> str:
    """Remove package declarations if any."""
    return re.sub(r"^\s*package\s+\S+\s*\n", "", src, flags=re.MULTILINE)


def strip_auto_marker(src: str) -> str:
    """Remove //%AUTO line from source."""
    lines = [l for l in src.splitlines(keepends=True) if l.strip() != "//%AUTO"]
    return "".join(lines)


def bundle(main_path: Path, out_path: Path) -> None:
    registry_sym = load_registry(REGISTRY_PATH)
    # sym_to_file already done by load_registry

    main_src = read_file(main_path)
    includes, excludes, has_auto = parse_directives(main_src)

    # Determine files to include
    files_to_include: set[str] = set(includes)

    if has_auto:
        refs = find_referenced_symbols(main_src, registry_sym)
        for sym in refs:
            files_to_include.add(registry_sym[sym])

    # Resolve dependencies
    ordered = resolve_deps(files_to_include, registry_sym, registry_sym)

    # Remove excluded
    ordered = [f for f in ordered if f not in excludes]

    # Build output
    parts: list[str] = []
    parts.append("// Auto-generated by tools/bundle.py — do not edit manually\n\n")

    for fpath in ordered:
        full_path = REPO_ROOT / fpath
        if not full_path.exists():
            continue
        src = strip_package(read_file(full_path))
        parts.append(f"// ---- {fpath} ----\n")
        parts.append(src.strip())
        parts.append("\n\n")

    # Append Main.kt body (without directives and //%AUTO)
    main_body = strip_auto_marker(main_src)
    # Remove //%include and //%exclude lines
    main_body_lines = [
        l for l in main_body.splitlines(keepends=True)
        if not l.strip().startswith("//%include ")
        and not l.strip().startswith("//%exclude ")
    ]
    parts.append("// ---- Main.kt ----\n")
    parts.append("".join(main_body_lines).strip())
    parts.append("\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write("".join(parts))

    print(f"Bundled {len(ordered)} file(s) → {out_path}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Bundle Kotlin CP library into single file.")
    parser.add_argument("main", nargs="?", default=str(DEFAULT_MAIN), help="Path to Main.kt")
    parser.add_argument("-o", "--output", default=str(DEFAULT_OUT), help="Output path")
    args = parser.parse_args()

    bundle(Path(args.main), Path(args.output))
